version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: yelp_postgres
    environment:
      POSTGRES_DB: yelp_sample
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: yelp_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: yelp_sample
      DB_PORT: 5432
      PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: