version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: yelp_postgres
    environment:
      POSTGRES_DB: yelp_sample
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  gateway:
    build: 
      context: .
      dockerfile: ./services/gateway/Dockerfile
    container_name: yelp_gateway
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      JWT_SECRET: "your-super-secret-jwt-key-change-in-production"
      AUTH_SERVICE_URL: "http://auth-service:8084"
    depends_on:
      - business-service
      - review-service
      - auth-service
    networks:
      - frontend
      - backend

  business-service:
    build: 
      context: .
      dockerfile: ./services/business/Dockerfile
    container_name: yelp_business_service
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: yelp_sample
      DB_PORT: 5432
      PORT: 8081
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend

  review-service:
    build: 
      context: .
      dockerfile: ./services/review/Dockerfile
    container_name: yelp_review_service
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: yelp_sample
      DB_PORT: 5432
      PORT: 8082
      LOGGING_SERVICE_URL: http://logging-service:8083
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend

  cassandra:
    image: cassandra:4.0
    container_name: yelp_cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: yelp_cluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - backend

  logging-service:
    build: 
      context: .
      dockerfile: ./services/logging/Dockerfile
    container_name: yelp_logging_service
    environment:
      PORT: 8083
      CASSANDRA_HOSTS: cassandra:9042
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - backend

  auth-service:
    build: 
      context: .
      dockerfile: ./services/auth/Dockerfile
    container_name: yelp_auth_service
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: yelp_sample
      DB_PORT: 5432
      PORT: 8084
      JWT_SECRET: "your-super-secret-jwt-key-change-in-production"
      JWT_EXPIRES_IN: "24h"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend


networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true

volumes:
  postgres_data:
  cassandra_data: