apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-service
  namespace: yelp-app
  labels:
    app: business-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: business-service
  template:
    metadata:
      labels:
        app: business-service
    spec:
      containers:
      - name: business-service
        image: yelp-business-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: yelp-config
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: yelp-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: yelp-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: yelp-config
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: yelp-config
              key: DB_PORT
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: yelp-config
              key: PORT_BUSINESS
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"