apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  namespace: yelp-app
  labels:
    app: cassandra
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:4.0
        ports:
        - containerPort: 9042
          name: cql
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        env:
        - name: CASSANDRA_CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: yelp-config
              key: CASSANDRA_CLUSTER_NAME
        - name: CASSANDRA_DC
          valueFrom:
            configMapKeyRef:
              name: yelp-config
              key: CASSANDRA_DC
        - name: CASSANDRA_RACK
          valueFrom:
            configMapKeyRef:
              name: yelp-config
              key: CASSANDRA_RACK
        - name: CASSANDRA_ENDPOINT_SNITCH
          valueFrom:
            configMapKeyRef:
              name: yelp-config
              key: CASSANDRA_ENDPOINT_SNITCH
        - name: MAX_HEAP_SIZE
          value: "512M"
        - name: HEAP_NEWSIZE
          value: "128M"
        volumeMounts:
        - name: cassandra-storage
          mountPath: /var/lib/cassandra
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - nodetool status
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - cqlsh -e "describe keyspaces"
          initialDelaySeconds: 90
          periodSeconds: 20
          timeoutSeconds: 15
          failureThreshold: 5
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: cassandra-storage
        persistentVolumeClaim:
          claimName: cassandra-pvc