apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
  namespace: yelp-app
  labels:
    app: cassandra
spec:
  type: ClusterIP
  ports:
  - port: 9042
    targetPort: 9042
    protocol: TCP
    name: cql
  selector:
    app: cassandra