apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: yelp-app
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: yelp-gateway:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: yelp-config
              key: PORT_GATEWAY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: yelp-secrets
              key: JWT_SECRET
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: yelp-config
              key: AUTH_SERVICE_URL
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"