apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-service
  namespace: yelp-app
  labels:
    app: logging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging-service
  template:
    metadata:
      labels:
        app: logging-service
    spec:
      containers:
      - name: logging-service
        image: yelp-logging-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: yelp-config
              key: PORT_LOGGING
        - name: CASSANDRA_HOSTS
          valueFrom:
            configMapKeyRef:
              name: yelp-config
              key: CASSANDRA_HOSTS
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"