apiVersion: v1
kind: Service
metadata:
  name: business-service
  namespace: yelp-app
  labels:
    app: business-service
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: business-service
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: yelp-app
  labels:
    app: review-service
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: review-service
---
apiVersion: v1
kind: Service
metadata:
  name: logging-service
  namespace: yelp-app
  labels:
    app: logging-service
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: http
  selector:
    app: logging-service
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: yelp-app
  labels:
    app: auth-service
spec:
  type: ClusterIP
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
    name: http
  selector:
    app: auth-service