apiVersion: v1
kind: Secret
metadata:
  name: yelp-secrets
  namespace: yelp-app
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=  # postgres (base64)
  DB_PASSWORD: cG9zdGdyZXM=  # postgres (base64)
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==  # your-super-secret-jwt-key-change-in-production (base64)