apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: replica-patch.yaml
  - path: resource-patch.yaml

labels:
  - pairs:
      environment: development